---

- name: install needed packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - tar
    - bzip2

- name: create prometheus system group
  group:
    name: "{{ prometheus_group }}"
    system: yes
    state: present

- name: create prometheus system user
  user:
    name: "{{ prometheus_user }}"
    system: yes
    shell: "/sbin/nologin"
    group: "{{ prometheus_group }}"
    createhome: no

- name: create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
  with_items:
    - "{{ prometheus_root_dir }}"
    - "{{ prometheus_dist_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_rules_dir }}"
    - "{{ prometheus_file_sd_config_dir }}"
    - "{{ prometheus_db_dir }}"

- name: create prometheus extra directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
  with_items:
    - "{{ prometheus_extra_dirs }}"

- name: download prometheus server binary
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/{{ prometheus_version }}/{{ prometheus_release_name }}.tar.gz"
    dest: "{{ prometheus_dist_dir }}"

- name: unarchive binary tarball
  unarchive:
    copy: no
    src: "{{ prometheus_dist_dir }}/{{ prometheus_release_name }}.tar.gz"
    dest: "{{ prometheus_dist_dir }}"
    creates: "{{ prometheus_dist_dir }}/{{ prometheus_release_name }}/prometheus"
  register: prometheus_updated
  notify:
    - restart prometheus

- name: update group and owner for files
  command: "chmod {{ prometheus_user}}:{{ prometheus_group }} -R {{ prometheus_release_name }}"
  when: prometheus_updated | changed
  
- name: create symlink to the current release
  file:
    src: "{{ prometheus_dist_dir }}/{{ prometheus_release_name }}"
    path: "{{ prometheus_root_dir }}/current"
    state: link

- name: created service environment file
  template:
    src: etc/default/prometheus.j2
    dest: /etc/default/prometheus
    owner: root
    group: root
    mode: 0644
  notify:
    - restart prometheus

- name: create systemd service unit
  template:
    src: etc/systemd/system/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify:
    - service reenable
    - restart prometheus

- name: ensure prometheus service is enabled
  service:
    name: prometheus
    enabled: yes

- name: include prometheus configuration
  include: configuration.yml
  tags: ['prometheus-configuration']
